version: "3.8"
services:
  backend:
    image: ghcr.io/boelgen/boelgen-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    # Resource limits to prevent container from consuming too much memory/CPU
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G